# Generated by Django 6.0.4 on 2026-04-16 19:57

from django.db import migrations


def migrate_author_to_contributors(apps, schema_migration):
    Blog = apps.get_model("blog", "Blog")
    for blog in Blog.objects.all():
        if blog.author:
            blog.contributors.add(
                blog.author, through_defaults={"contribution": "Auteur principal"}
            )


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_author_blogcontributor_blog_contributors"),
    ]

    operations = [migrations.RunPython(migrate_author_to_contributors)]
